### ISSUE TITLE
Missing export of `NgcCookieOptions`

### ISSUE THREAD

**Issue by pawod** [tinesoft/ngx-cookieconsent#53]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version:        3.1.1
- ngx-cookieconsent version:    2.2.1
```

### OS Version?
Windows 10

### Angular, Node and al Versions?
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15

@angular-devkit/architect             0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer  0.13.9
@angular-devkit/build-webpack   0.13.9
@angular-devkit/core                    7.3.9
@angular-devkit/schematics         7.3.9
@angular/cli                                  7.3.9
@ngtools/webpack                       7.3.9
@schematics/angular                    7.3.9
@schematics/update                     0.13.9
rxjs                                                 6.3.3
typescript                                       3.2.4
webpack                                        4.29.0

npm                                               6.4.1

### Repro steps
- try to import and use `NgcCookieOptions` like
 `import { NgcCookieOptions } from 'ngx-cookieconsent';`

- adding `NgcCookieOptions` to the export statement of `index.ts` fixes the issue

### The log given by the failure
> ERROR in src/app/app.component.ts(4,54): error TS2724: Module '"<project_root>/node_modules/ngx-cookieconsent/ngx-cookieconsent"' has no exported member 'NgcCookieOptions'

### Desired functionality
`NgcCookieOptions` should be exported by `index.ts`

**Comment by tinesoft** [comment]
Hi @pawod ,

Thanks for using the library, and good catch!
Just released v2.2.2 with the fix :)


Happy hacking!

**Comment by pawod** [comment]
Hi @tinesoft ,

I think something went wrong with your package build. After updating to v2.2.2 the `build` folder is missing in `..\node_modules\ngx-cookieconsent`.

**Comment by pawod** [comment]
Hi @tinesoft,

after updating to v2.2.2 I get following runtime errors, when loading the app and I'm not sure whether it's a configuration issue or not (I'm not aware of having changed anything, besides updating the node package):

> Uncaught SyntaxError: Unexpected token export (scripts.js:7)

> ERROR TypeError: Cannot read property 'initialise' of undefined (AppComponent_Host.ngfactory.js? [sm]:1)
>     at NgcCookieConsentService.push../node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js.NgcCookieConsentService.init (ngx-cookieconsent.es5.js:149)
>     at new NgcCookieConsentService (ngx-cookieconsent.es5.js:96)
>     at _createClass (core.js:21265)
>     at _createProviderInstance (core.js:21235)
>     at resolveNgModuleDep (core.js:21199)
>     at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21907)
>     at resolveDep (core.js:22278)
>     at createClass (core.js:22152)
>     at createDirectiveInstance (core.js:22029)
>     at createViewNodes (core.js:23255)
> View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
> proxyClass @ compiler.js:18239
> push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
> push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
> (anonymous) @ core.js:17870
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
> (anonymous) @ core.js:17870
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> onInvoke @ core.js:17299
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> (anonymous) @ zone.js:889
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
> onInvokeTask @ core.js:17290
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
> push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
> drainMicroTaskQueue @ zone.js:601
> push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
> invokeTask @ zone.js:1744
> globalZoneAwareCallback @ zone.js:1781
> load (async)
> customScheduleGlobal @ zone.js:1883
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
> onScheduleTask @ zone.js:301
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:264
> (anonymous) @ zone.js:2054
> (anonymous) @ http.js:1713
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:43
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:29
> (anonymous) @ subscribeTo.js:21
> subscribeToResult @ subscribeToResult.js:11
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub @ mergeMap.js:74
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext @ mergeMap.js:68
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next @ mergeMap.js:51
> push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
> (anonymous) @ scalar.js:5
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:43
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:29
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call @ mergeMap.js:29
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
> push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call @ filter.js:15
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
> push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call @ map.js:18
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
> (anonymous) @ Observable.js:98
> ZoneAwarePromise @ zone.js:910
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.toPromise @ Observable.js:96
> push../src/app/app-config.service.ts.AppConfigService.loadAppConfig @ app-config.service.ts:20
> (anonymous) @ app.module.ts:58
> push../node_modules/@angular/core/fesm5/core.js.ApplicationInitStatus.runInitializers @ core.js:16739
> (anonymous) @ core.js:17774
> _callAndReportToErrorHandler @ core.js:17867
> (anonymous) @ core.js:17772
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> onInvoke @ core.js:17299
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:17213
> push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory @ core.js:17763
> (anonymous) @ core.js:17803
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> (anonymous) @ zone.js:889
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
> push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
> drainMicroTaskQueue @ zone.js:601
> Promise.then (async)
> scheduleMicroTask @ zone.js:584
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
> scheduleResolveOrReject @ zone.js:879
> ZoneAwarePromise.then @ zone.js:1012
> push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:17803
> ./src/main.ts @ main.ts:11
> __webpack_require__ @ bootstrap:83
> 0 @ main.ts:12
> __webpack_require__ @ bootstrap:83
> checkDeferredModules @ bootstrap:45
> webpackJsonpCallback @ bootstrap:32
> (anonymous) @ main.js:1
> Show 39 more frames
> AppComponent_Host.ngfactory.js? [sm]:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
> View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
> proxyClass @ compiler.js:18239
> push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
> push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15777
> (anonymous) @ core.js:17870
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
> (anonymous) @ core.js:17870
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> onInvoke @ core.js:17299
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> (anonymous) @ zone.js:889
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
> onInvokeTask @ core.js:17290
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
> push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
> drainMicroTaskQueue @ zone.js:601
> push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
> invokeTask @ zone.js:1744
> globalZoneAwareCallback @ zone.js:1781
> load (async)
> customScheduleGlobal @ zone.js:1883
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
> onScheduleTask @ zone.js:301
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:264
> (anonymous) @ zone.js:2054
> (anonymous) @ http.js:1713
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:43
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:29
> (anonymous) @ subscribeTo.js:21
> subscribeToResult @ subscribeToResult.js:11
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub @ mergeMap.js:74
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext @ mergeMap.js:68
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next @ mergeMap.js:51
> push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
> (anonymous) @ scalar.js:5
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:43
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:29
> push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call @ mergeMap.js:29
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
> push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call @ filter.js:15
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
> push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call @ map.js:18
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
> (anonymous) @ Observable.js:98
> ZoneAwarePromise @ zone.js:910
> push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.toPromise @ Observable.js:96
> push../src/app/app-config.service.ts.AppConfigService.loadAppConfig @ app-config.service.ts:20
> (anonymous) @ app.module.ts:58
> push../node_modules/@angular/core/fesm5/core.js.ApplicationInitStatus.runInitializers @ core.js:16739
> (anonymous) @ core.js:17774
> _callAndReportToErrorHandler @ core.js:17867
> (anonymous) @ core.js:17772
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> onInvoke @ core.js:17299
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:17213
> push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory @ core.js:17763
> (anonymous) @ core.js:17803
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> (anonymous) @ zone.js:889
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
> push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
> drainMicroTaskQueue @ zone.js:601
> Promise.then (async)
> scheduleMicroTask @ zone.js:584
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
> scheduleResolveOrReject @ zone.js:879
> ZoneAwarePromise.then @ zone.js:1012
> push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:17803
> ./src/main.ts @ main.ts:11
> __webpack_require__ @ bootstrap:83
> 0 @ main.ts:12
> __webpack_require__ @ bootstrap:83
> checkDeferredModules @ bootstrap:45
> webpackJsonpCallback @ bootstrap:32
> (anonymous) @ main.js:1
> Show 39 more frames
> main.ts:12 TypeError: Cannot read property 'initialise' of undefined
>     at NgcCookieConsentService.push../node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js.NgcCookieConsentService.init (ngx-cookieconsent.es5.js:149)
>     at new NgcCookieConsentService (ngx-cookieconsent.es5.js:96)
>     at _createClass (core.js:21265)
>     at _createProviderInstance (core.js:21235)
>     at resolveNgModuleDep (core.js:21199)
>     at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21907)
>     at resolveDep (core.js:22278)
>     at createClass (core.js:22152)
>     at createDirectiveInstance (core.js:22029)
>     at createViewNodes (core.js:23255)
